#!/usr/bin/env python
#-*- coding:utf-8 -*-
import os
from ks3.connection import Connection
ak = 'AKLTShXQG7kWRMqY4wgPEeL8fg'
sk = 'OGXAS5f25lQeGLJfVNtaNWU0b6HG+EOJOFZMzoFsbwoXI0cDvFBPB3XYHfAkzkHVDg=='
c = Connection(ak, sk, host='ks3-cn-shanghai.ksyun.com', is_secure=False, domain_mode=False)
bucket_name = "ymz"

upload_dir = "test/"
if not os.path.exists("urlFILE.txt"):
    print("urlFILE.txt 文件不存在!!!")
    exit(1)

with open('urlFILE.txt','r') as f:
    content = f.readlines()
    #print(content)
    for f_n in content:
        file_name = "/data/rsync/client/" + "test/" + f_n.split("\n")[0]
        key_name = upload_dir + f_n.split("\n")[0]
        try:
            b = c.get_bucket(bucket_name)
            k = b.new_key(key_name)
            print("正在上传:%s"%file_name)
            ret=k.set_contents_from_filename(file_name, policy="private")
            if ret and ret.status != 200:
                raise ("上传失败")
        except Exception as ex:
            print(ex)
            exit(1)

    if(os.path.exists("urlFILE.txt")):
        os.remove("urlFILE.txt")
    else:
        print("没有urlFILE.txt文件")
